global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Product Service
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Inventory Service
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Order Service
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Supplier Service
  - job_name: 'supplier-service'
    static_configs:
      - targets: ['supplier-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Audit Service
  - job_name: 'audit-service'
    static_configs:
      - targets: ['audit-service:8007']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # File Service
  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:8009']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Analytics Service
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8010']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node Exporter (System metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']