interface ImportMetaEnv {
  VITE_API_URL: string;
  VITE_CLERK_PUBLISHABLE_KEY: string;
  VITE_SOCKET_PATH: string;
  VITE_SECURITY_SIGNATURE_SECRET: string;
  VITE_SECURITY_TIMESTAMP_TOLERANCE: string;
  VITE_SECURITY_NONCE_TIMEOUT: string;
  VITE_RATE_LIMIT_WINDOW: string;
  VITE_RATE_LIMIT_MAX_REQUESTS: string;
  VITE_ENABLE_REQUEST_LOGGING: string;
  VITE_ENABLE_PERFORMANCE_METRICS: string;
}
